[project]
name = "task-brokers"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "celery>=5.6.2",
    "redis>=7.1.0",
    "requests>=2.32.5",
]
